spring:
  application:
    name: transaction-batch-master
  main:
    allow-bean-definition-overriding: true
  
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: amit
    password: Welcome123
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      transaction-isolation: TRANSACTION_READ_COMMITTED
      auto-commit: false
  
  batch:
    jdbc:
      initialize-schema: never  # Changed from 'always' to 'never' - tables should be created manually or via migration tool
      isolation-level-for-create: read_committed
    job:
      enabled: false
  
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

aws:
  region: ap-south-1
  sqs:
    queue:
      name: amit-transaction-file-queue

s3:
  bucket:
    name: amit-transaction-files

kafka:
  topic:
    partition: amit-transaction-partitions

server:
  port: 8084

logging:
  level:
    com.transaction.batch: DEBUG
    org.springframework.batch: INFO